version: '3.7'

services:
  web:
    build: .
    env_file:
     - ./.env.web
     - ./.env.db
    volumes:
      - ./fixtures.json:/home/worker/fixtures.json
      - static_volume:/home/worker/static/
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
     - ./.env.db
    environment:
      - LANG:'ru_RU.UTF-8'
      - LANGUAGE:'ru_RU.UTF-8'
      - LC_ALL:'ru_RU.UTF-8'
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - db-data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/yamdb/static/
    ports:
    - 80:80
    depends_on:
    - web
volumes:
  static_volume:
  db-data:
