# Generated by Django 3.0.5 on 2020-12-13 21:09

import django.core.validators
from django.db import migrations, models
import titles.models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=titles.models.get_year, validators=[django.core.validators.MaxValueValidator(titles.models.get_year)]),
        ),
    ]
