# Generated by Django 3.1 on 2020-11-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
        ('comments', '0002_comments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title'),
        ),
    ]
