# Generated by Django 3.0.5 on 2021-02-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
