#!/bin/bash
set -e

psql -c "CREATE DATABASE ${SQL_DATABASE}";
psql -c "CREATE USER ${SQL_USER} WITH ENCRYPTED PASSWORD '${SQL_PASSWORD}'";
psql -c "GRANT ALL PRIVILEGES ON DATABASE ${SQL_DATABASE} TO ${SQL_USER}";

